# Setup
title:        Elixir - CS 2212 Team 4
tagline:      Textbook Bidding Project
baseurl:      "/Elixir/"
paginate:     1

# About/contact
author:
  name:       Abdulla Ouda
  url:        http://aouda6.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
